services:
  # Backend (Ruby on Rails)
  backend:
    build: ./productos_backend
    ports:
      - "3000:3000"  # Puerto de Rails
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/productos_backend_development
    depends_on:
      - db
    volumes:
      - ./productos_backend:/app
      - bundle_data:/usr/local/bundle  # Cache de gems
      - /app/tmp/pids 

  # Frontend (React con Vite)
  frontend:
    build: ./productos_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
      - NODE_ENV=development  # Añade esto
    volumes:
      - ./productos_frontend/src:/app/src  # Solo monta el código
      - ./productos_frontend/public:/app/public
      - /app/node_modules  # Elimina el volumen persistente de node_modules


  # Base de datos PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=productos_backend_development
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos


  jenkins:
    build:
      context: ./  # Ruta actual (donde está el Dockerfile-jenkins)
      dockerfile: Dockerfile-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
  jenkins_home:
  bundle_data:
  node_modules: