services:
  # Backend (Ruby on Rails)
  backend:
    build: ./productos_backend
    ports:
      - "3000:3000"  # Puerto de Rails
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/productos_backend_development
    depends_on:
      - db
    volumes:
      - ./productos_backend:/app
      - bundle_data:/usr/local/bundle  # Cache de gems

  # Frontend (React con Vite)
  frontend:
    build: ./productos_frontend
    ports:
      - "5173:5173"  # Puerto de Vite
    environment:
      - VITE_API_URL=http://backend:3000  # URL del backend
    depends_on:
      - backend
    volumes:
      - ./productos_frontend:/app
      - node_modules:/app/node_modules  # Cache de node

  # Base de datos PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=productos_backend_development
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos


  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"  
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  #Le permitimos a Jenkins usar Docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    user: root  # Evitamos problemas de permisos y accedemos sin problemas
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
  jenkins_home:
  bundle_data:
  node_modules: